### ISSUE TITLE
'new' without a 'delete'

### ISSUE THREAD

**Issue by fyh** [lambdataro/FLTK-Minesweeper#1]
In [GameWindow.cpp#L439](https://github.com/lambdataro/FLTK-Minesweeper/blob/master/GameWindow.cpp#L439), 'new' without a 'delete' appears.

I am new to FLTK and confused with this, will that cause a memory leak or not? Why?

**Comment by lambdataro** [comment]
It will not cause a memory leak.
The GameWindow class inherits the Fl_Window class
and its lifetime is managed by FLTK event loop.
